"""
    MILP

Represent a Mixed Integer Linear Program in "cuPDLPx form":

    min cᵀx   s.t.   lv ≤ x ≤ uv
                     lc ≤ A * x ≤ uc

# Constructor

    MILP(;
        c, lv, uv, A, lc, uc,
        At=sametype_transpose(A),
        [D1, D2, int_var, var_names, dataset, name, path]
    )

# Fields

$(TYPEDFIELDS)
"""
struct MILP{
        T <: Number,
        Vo <: AbstractVecOrMat{T},
        Vv <: AbstractVecOrMat{T},
        Vc <: AbstractVecOrMat{T},
        V <: AbstractVector{T},
        M <: AbstractArray{T},
        Mt <: AbstractArray{T},
        Vb <: DenseVector{Bool},
    }
    "objective vector"
    c::Vo
    "variable lower bound"
    lv::Vv
    "variable upper bound"
    uv::Vv
    "constraint matrix"
    A::M
    "transposed constraint matrix"
    At::Mt
    "constraint lower bound"
    lc::Vc
    "constraint upper bound"
    uc::Vc
    "left preconditioner"
    D1::Diagonal{T, V}
    "right preconditioner"
    D2::Diagonal{T, V}
    "which variables must be integers"
    int_var::Vb
    "variable names"
    var_names::Vector{String}
    "source dataset"
    dataset::String
    "instance name (last part of the path)"
    name::String
    "file path the MILP was read from"
    path::String

    function MILP(;
            c,
            lv,
            uv,
            A,
            At = sametype_transpose(A),
            lc,
            uc,
            D1 = Diagonal(one!(similar(lc, size(lc, 1)))),
            D2 = Diagonal(one!(similar(lv, size(lv, 1)))),
            int_var = zero!(similar(c, Bool, size(c, 1))),
            var_names = map(string, axes(c, 1)),
            dataset = "",
            name = "",
            path = ""
        )
        m, n = size(A)
        if !(n == size(c, 1) == size(lv, 1) == size(uv, 1) == size(D2, 1) == length(int_var) == length(var_names))
            throw(DimensionMismatch("Variable size not consistent"))
        elseif !(m == size(lc, 1) == size(uc, 1) == size(D1, 2))
            throw(DimensionMismatch("Constraint size not consistent"))
        else
            size(lv, 2) == size(uv, 2) || throw(DimensionMismatch("Batch size not consistent"))
            size(lc, 2) == size(uc, 2) || throw(DimensionMismatch("Batch size not consistent"))
            nbinst = 1
            for v in (c, lv, lc)
                size(v, 2) == 1 && continue
                if nbinst == 1
                    nbinst = size(v, 2)
                elseif nbinst != size(v, 2)
                    throw(DimensionMismatch("Batch size not consistent"))
                end
            end
        end

        T = Base.promote_eltype(c, lv, uv, A, At, lc, uc, D1, D2)
        M = typeof(A)
        Mt = typeof(At)
        Vb = typeof(int_var)

        if (
                !isconcretetype(T) ||
                    !isconcretetype(M) ||
                    !isconcretetype(Mt) ||
                    !isconcretetype(Vb)
            )
            throw(ArgumentError("Abstract type parameter"))
        end

        common_backend(c, lv, uv, A, At, lc, uc, D1, D2)

        if isempty(name) && !isempty(path)
            name = splitext(splitpath(path)[end])[1]
        end

        return new{T, typeof(c), typeof(lv), typeof(lc), typeof(diag(D1)), M, Mt, Vb}(
            c,
            lv,
            uv,
            A,
            At,
            lc,
            uc,
            D1,
            D2,
            int_var,
            var_names,
            string(dataset),
            string(name),
            string(path)
        )
    end
end

"""
    MILP(qps::QPSData; kwargs...)

Construct a [`MILP`](@ref) from a `QPSData` object generated by [QPSReader.jl](https://github.com/JuliaSmoothOptimizers/QPSReader.jl).
"""
function MILP(qps::QPSData; kwargs...)
    return MILP(;
        c = qps.c,
        lv = qps.lvar,
        uv = qps.uvar,
        A = sparse(qps.arows, qps.acols, qps.avals, length(qps.lcon), length(qps.lvar)),
        At = sparse(qps.acols, qps.arows, qps.avals, length(qps.lvar), length(qps.lcon)),
        lc = qps.lcon,
        uc = qps.ucon,
        D1 = Diagonal(ones(length(qps.lcon))),
        D2 = Diagonal(ones(length(qps.lvar))),
        int_var = convert(Vector{Bool}, (qps.vartypes .== VTYPE_Binary) .| (qps.vartypes .== VTYPE_Integer)),
        var_names = qps.varnames,
        kwargs...
    )
end

function Base.show(io::IO, milp::MILP{T, Vo, Vv, Vc, V, M, Mt}) where {T, Vo, Vv, Vc, V, M, Mt}
    return print(
        io, """
        MILP instance $(milp.name) from dataset $(milp.dataset):
        - types:
          - values $T
          - vectors $(Vo == Vv == Vc ? Vo : (Vo, Vv, Vc))
          - matrices $(M == Mt ? M : (M, Mt))
        - variables: $(nbvar(milp))
          - $(nbvar_cont(milp)) continuous
          - $(nbvar_int(milp)) integer
        - constraints: $(nbcons(milp))
          - $(nbcons_ineq(milp)) inequalities
          - $(nbcons_eq(milp)) equalities
        - nonzeros: $(mynnz(milp.A))"""
    )
end

KernelAbstractions.get_backend(milp::MILP) = get_backend(milp.c)

"""
    nbvar(milp)

Return the number of variables in `milp`.
"""
nbvar(milp::MILP) = size(milp.c, 1)

"""
    nbvar_int(milp)

Return the number of integer variables in `milp`.
"""
nbvar_int(milp::MILP) = sum(milp.int_var)

"""
    nbvar_cont(milp)

Return the number of continuous variables in `milp`.
"""
nbvar_cont(milp::MILP) = nbvar(milp) - nbvar_int(milp)

"""
    nbcons(milp)

Return the number of constraints in `milp`, not including variable bounds or integrality requirements.
"""
nbcons(milp::MILP) = size(milp.A, 1)

"""
    nbcons_eq(milp)

Return the number of equality constraints in `milp`.
"""
nbcons_eq(milp::MILP) = mapreduce(==, +, milp.lc, milp.uc)

"""
    nbcons_ineq(milp)

Return the number of inequality constraints in `milp`, not including variable bounds.
"""
nbcons_ineq(milp::MILP) = nbcons(milp) - nbcons_eq(milp)

function Base.isapprox(m1::MILP, m2::MILP; kwargs...)
    return (
        isapprox(m1.c, m2.c; kwargs...) &&
            isapprox(m1.lv, m2.lv; kwargs...) &&
            isapprox(m1.uv, m2.uv; kwargs...) &&
            isapprox(m1.A, m2.A; kwargs...) &&
            isapprox(m1.At, m2.At; kwargs...) &&
            isapprox(m1.lc, m2.lc; kwargs...) &&
            isapprox(m1.uc, m2.uc; kwargs...) &&
            isapprox(m1.D1, m2.D1; kwargs...) &&
            isapprox(m1.D2, m2.D2; kwargs...) &&
            m1.int_var == m2.int_var &&
            m1.var_names == m2.var_names &&
            m1.dataset == m2.dataset &&
            m1.name == m2.name &&
            m1.path == m2.path
    )
end

function nbinstances((; c, lv, lc, A)::MILP)
    return max(size(c, 2), size(lv, 2), size(lc, 2), size(A, 3))
end

"""
    isbatched(milp)

Return whether `milp` holds a batch of instances rather than a single one.

Unlike [`nbinstances`](@ref), this only depends on the type of `milp`, so it is a constant as
far as inference is concerned and the shape of the arrays attached to `milp` follows from it.
"""
function isbatched((; c, lv, lc, A)::MILP)
    return ndims(c) > 1 || ndims(lv) > 1 || ndims(lc) > 1 || ndims(A) > 2
end
function instance(milp::MILP, i::Int)
    return MILP(;
        c = instance_vec(milp.c, i),
        lv = instance_vec(milp.lv, i),
        uv = instance_vec(milp.uv, i),
        A = instance_mat(milp.A, i),
        At = instance_mat(milp.At, i),
        lc = instance_vec(milp.lc, i),
        uc = instance_vec(milp.uc, i),
        D1 = milp.D1,
        D2 = milp.D2,
        int_var = milp.int_var,
        var_names = milp.var_names,
        dataset = milp.dataset,
        name = milp.name,
        path = milp.path
    )
end
